spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev


# printing only for error else not to print anthing in console
# logging:
#   level:
#     root: OFF


#setting custom logging levels 
logging:
  level:
    com:
      learningBoot:
        demo:
          service:
            UserEntryService: DEBUG
            JournalEntryService: INFO
          controller:
            JournalEntryController: ERROR
          
            








